### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by mustafaarun** [SharpeRAD/Glimpse.LightInject#1]
glimpse is enabled on container but here is the error on glimpse console : 

System.NullReferenceException: Object reference not set to an instance of an object. at System.Object.GetType() at Glimpse.LightInject.LightInjectGlimpsePlugin.<>c.b__6_0(ServiceRegistration registration) at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection) at Glimpse.LightInject.LightInjectGlimpsePlugin.GetData(ITabContext context) at Glimpse.Core.Framework.GlimpseRuntime.ExecuteTabs(RuntimeEvent runtimeEvent)

**Comment by SharpeRAD** [comment]
Closing as you have not provided an example.
